FROM ubuntu:14.04

RUN sudo apt-get update \
  && apt-get -y install xfonts-100dpi xfonts-75dpi xfonts-cyrillic xorg dbus-x11 libqt4-webkit libqt4-dev g++ xvfb cutycapt

COPY fonts /usr/share/fonts/win
RUN  chmod 644 /usr/share/fonts/win/* && mkfontscale && mkfontdir && fc-cache -fv